### ISSUE TITLE
iOS10 聊天输入框输入文字光标来回闪动

### ISSUE THREAD

**Issue by RondaHo** [gyjzh/LLWeChat#1]
非常棒的仿微信项目。在我注意的几个细节上确实做到了微信的效果，还有超越。
比如键盘弹出的时候，长按某条消息，复制删除等菜单依然正常弹出，不会造成键盘收起。这些很小的细节作者都照顾到了。
唯一有点缺陷的可能就是控制器里面堆的代码有点多。不好查看
作者应该不是用的xcode8编译的把，怎么感觉没有适配iOS10呢。比如推送在iOS10需要打开push notification开关，不然无法注册APNs推送，无法获取token。iOS10上的注册通知的API也有所改变。需要使用UNUserNotificationCenter
好了，这些不是重点。为了让项目跑起来，我特意去高德、环信注册了应用。并且成功配置。通信这块确实做得蛮好。就是在iOS10的手机上输入框的光标在输入文字的时候回来回闪动，特别影响体验

**Comment by gyjzh** [comment]
原项目是不支持IOS10的，我手机升级IOS10后接到公司面试通知，为了让项目在手机上跑起来，只是粗略地适配了IOS10，不至于项目在IOS10上奔溃，其他针对IOS10的适配全部没做。现在工作有点急，暂时不打算在这个项目上投入时间了，等有时间了，再做适配、代码拆分等工作吧

**Comment by ZWZZZ** [comment]
ios10上面输入框的光标在输入文字的时候的确会来回闪动
